version: '3.7'

services:
  api:
    container_name: api
    build: 
      context: ../api/
      dockerfile: ../api/docker/node/Dockerfile
    env_file:
      - .env
    volumes:
      - ../api/:/app
      - ../api/docker/logs/node/:/app/logs
    ports:
      - 5000:5000
      - 9229:9229
    command: ["make"]
    depends_on:
      - postgres
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - PG_DATA=/var/lib/postgresql/PG_DATA
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ../api/docker/db:/var/lib/postgresql/data
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: ../frontend/docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ../frontend/:/frontend
    command: ["make"]
    restart: unless-stopped
    